version: '3.2'
services:
  sdswatch-client:
    image: docker.elastic.co/beats/filebeat:7.7.0
    container_name: sdswatch-client
    user: ${HOST_UID}:${HOST_GID}
    environment:
      - "HOST=${HOST}"
    volumes:
      - /data/work/jobs:/jobs
      - /export/home/hysdsops/verdi/log:/verdi/
      - /export/home/hysdsops/verdi/etc/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /export/home/hysdsops/verdi/etc/configs/:/usr/share/filebeat/configs/
      - /export/home/hysdsops/verdi/share/filebeat-sdswatch-client/data:/usr/share/filebeat/data
